<MainWindow>:
    orientation: 'horizontal'
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 0.9, 1
        id: racing_track
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'racetrack0001.png'
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: 0.1, 1
        MDLabel:
            text: 'Bavo'
        MDLabel:
            text: root.dashboard_speed

