name: Build AAB Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: BikeChainSwapApp  

    - name: Change Directory
      run: cd BikeChainSwapApp

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-setuptools \
          python3-venv \
          python3-dev \
          libssl-dev \
          libffi-dev
        pip install -r requirements.txt

    - name: Build AAB Package
      run: |
        buildozer init
        buildozer android release
