name: Build BikeChainSwapApp
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Android app
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-29t

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: Kivy_examples  # Specify the target directory for checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-pip python3-setuptools python3-dev

      - name: Install Kivy Dependencies
        run: |
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

      - name: Install aidl
        run: |
          sudo apt-get install -y aidl

      - name: Install Python packages
        run: |
          cd Kivy_examples/BikeChainSwapApp
          pip install -r requirements.txt
  
      - name: Build AAB
        run: |
          cd Kivy_examples/BikeChainSwapApp
          buildozer android release
