name: Build BikeChainSwapApp
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: Kivy_examples  # Specify the target directory for checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-pip python3-setuptools python3-dev

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc
          source ~/.bashrc

      - name: Install Kivy Dependencies
        run: |
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

      - name: Install Android SDK Build-Tools and Accept Licenses
        run: |
          echo "y" | sdkmanager "build-tools;35.0.0-rc1" --licenses

      - name: Install aidl
        run: |
          sudo apt-get install -y aidl

      - name: Install Python packages
        run: |
          cd Kivy_examples/BikeChainSwapApp
          pip install -r requirements.txt
  
      - name: Build AAB
        run: |
          cd Kivy_examples/BikeChainSwapApp
          buildozer android release
